### ISSUE TITLE
MongoError: QueryFailure flag set on getmore command

### ISSUE THREAD

**Issue by lexieheinle** [thebuffalonews/chart-tool#14]
Potentially related to this https://github.com/Automattic/monk/issues/107
`Exception while polling query {"collectionName":"charts","selector":{},"options":{"transform":null,"sort":{"lastEdited":-1},"limit":24,"fields":{"img":true,"slug":true,"lastEdited":true}}}: MongoError: QueryFailure flag set on getmore command
    at Object.Future.wait (/var/www/bundle/programs/server/node_modules/fibers/future.js:420:15)
    at SynchronousCursor._nextObject (packages/mongo/mongo_driver.js:986:47)
    at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1020:22)
    at SynchronousCursor.getRawObjects (packages/mongo/mongo_driver.js:1069:12)
    at PollingObserveDriver._pollMongo (packages/mongo/polling_observe_driver.js:152:48)
    at Object.task (packages/mongo/polling_observe_driver.js:90:12)
    at [object Object]._.extend._run (packages/meteor/fiber_helpers.js:147:1)
    at packages/meteor/fiber_helpers.js:125:1
    - - - - -
    at Object.toError (/var/www/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/utils.js:114:11)
    at /var/www/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/cursor.js:853:31
    at /var/www/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1905:9
    at Server.Base._callHandler (/var/www/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
    at /var/www/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:488:18
    at [object Object].MongoReply.parseBody (/var/www/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at [object Object].<anonymous> (/var/www/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:446:20)
    at [object Object].emit (events.js:95:17)
    at [object Object].<anonymous> (/var/www/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)
    at [object Object].emit (events.js:98:17)
`

**Comment by lexieheinle** [comment]
Fixed by running `db.charts.createIndex({"lastEdited": -1})`
